---
title: "SpatialData_and_Mapping"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{R - Install Packages}
install.packages("raster")
install.packages("rgdal")
install.packages("sp")
install.packages("rgeos")
install.packages("spatial")
install.packages("GISTools")
install.packages("maptools")
install.packages("spatstat")
install.packages("randomForest")
install.packages("sf")
install.packages("Stats")
install.packages("tidyverse")
install.packages("magrittr")
install.packages("lintr")
install.packages("viridis")
install.packages("cowplot")
install.packages("rmarkdown")

require(raster)
require(rgdal)
require(sp)
require(rgeos)
require(spatial)
require(GISTools)
require(dplyr)
require(maptools)
require(spatstat)
require(randomForest)
require(sf)
require(stats)
require(tidyverse)
require(magrittr)
require(lintr)
require(viridis)
require(cowplot)
require(rmarkdown)

# All good
```

# Working off of Chloe's desktop GIS workspace
```{r - Set Working Directory}
# Chloe's desktop
setwd("C:/Users/Invasion Lab/Desktop/SpatialDataandMapping")

```

# Load Vector Data
```{r - Load Vector Data}

# Read in dataset of leafy spurge presence points in Fremont Co, WY
SpurgeFull <- readOGR(dsn = "C:/Users/Invasion Lab/Desktop/SpatialDataandMapping", layer = "SpurgeFull")
bbox(SpurgeFull)

# Plot dataset
plot(SpurgeFull)

# Not that informative, add some spatial context with Fremont Co border
FremontCo <- readOGR(dsn = "C:/Users/Invasion Lab/Desktop/SpatialDataandMapping", layer = "FremontCo")
StudyExtent <- readOGR(dsn = "C:/Users/Invasion Lab/Desktop/SpatialDataandMapping", layer = "FremontBuff1000m")
bbox(FremontCo)
bbox(StudyExtent)

# Check coordinate system and projection, otherwise these will not align
proj4string(SpurgeFull)
st_crs(SpurgeFull)
# "+proj=tmerc +lat_0=40.5 +lon_0=-108.75 +k=0.9999375 +x_0=600000 +y_0=0 +datum=NAD83 +units=us-ft +no_defs"
# That's UTM NAD1983, more specifically, this uses the Wyoming State Plane
# This would probably be appropriate for the scale of our dataset, but will result in a stretched out map
# Could find a better option... Let's roll unprojected for now, just lat long
SpurgeFull <- spTransform(SpurgeFull, CRS("+proj=longlat +datum=WGS84 +no_defs"))
plot(SpurgeFull)
# Check the county layer
proj4string(FremontCo)
proj4string(StudyExtent)
# WGS84, no projection... Keep that for now

bbox(StudyExtent)
Bbox <- bbox

# Have to fortify to plot with ggplot
FremontCoF <- fortify(FremontCo)
StudyExtentF <- fortify(FremontCo)
SpurgeFullF <- fortify(SpurgeFull)

# Plot them together, finally
BaseMap <- ggplot() +
  geom_polygon(data = FremontCoF, aes(x=long, y=lat)) +
  geom_polygon(data = SpurgeFullF, aes(x=long, y=lat, group = group), fill = "NA", color = "yellow")
plot(BaseMap)

# Import and adjust all other vector data

# Read in county roads
FremontCoRoad <- readOGR(dsn = "C:/Users/Invasion Lab/Desktop/SpatialDataandMapping", layer = "FremontCoRoad")
# Check projection
st_crs(FremontCoRoad)
proj4string(FremontCoRoad)
# Fortify
FremontCoRoadF <- fortify(FremontCoRoad)
# Plot dataset
ggplot() +
  geom_polygon(data = FremontCoF, aes(x=long, y=lat)) +
  geom_line(data = FremontCoRoadF, aes(x=long, y=lat, group = group), fill = "NA", color = "white" )
# This  dataset is HUGE, cut it down to just the main roads

# Read in main roads
FremontMRoads <- readOGR(dsn = "C:/Users/Invasion Lab/Desktop/SpatialDataandMapping", layer = "FremontMainRoads")
# Check projection
st_crs(FremontMRoads)
proj4string(FremontMRoads)
# Fortify
FremontMRoadsF <- fortify(FremontMRoads)
# Plot dataset
ggplot() +
  geom_polygon(data = FremontCoF, aes(x=long, y=lat)) +
  geom_line(data = FremontMRoadsF, aes(x=long, y=lat, group = group), fill = "NA", color = "white" )

# Read in waterways
FremontWater <- readOGR(dsn = "C:/Users/Invasion Lab/Desktop/SpatialDataandMapping", layer = "WaterwaysFremont")
# Check projection
proj4string(FremontWater)
# Fortify
FremontWaterF <- fortify(FremontWater)
# Plot dataset
ggplot() +
  geom_polygon(data = FremontCoF, aes(x=long, y=lat)) +
  geom_line(data = FremontMRoadsF, aes(x=long, y=lat, group = group), fill = "NA", color = "white" ) +
  geom_polygon(data = FremontWaterF, aes(x=long, y=lat, group = group), fill = "blue", color = "blue" )

# Read in public land management areas
FremontAgencies <- readOGR(dsn = "C:/Users/Invasion Lab/Desktop/SpatialDataandMapping", layer = "FremontAgencies")
# Check projection
proj4string(FremontAgencies)
# Fortify
FremontAgenciesF <- fortify(FremontAgencies)
# Plot dataset
# ggplot() +
  # geom_polygon(data = FremontCoF, aes(x=long, y=lat)) +
  # geom_polygon(data = FremontAgenciesF, aes(x=long, y=lat, fill = id, group = group), color = "black") +
  # geom_line(data = FremontMRoadsF, aes(x=long, y=lat, group = group), fill = "NA", color = "white" ) +
  # geom_polygon(data = FremontWaterF, aes(x=long, y=lat, group = group), fill = "NA", color = "blue" )
plot(FremontAgencies)

```

# Load Raster Data
```{r Import Raster Data}
# For this project, we have three continuous topographic rasters and one thematic landcover raster

# Import elevation
Elevation <- raster("elev_output.tif")
st_crs(Elevation)
plot(Elevation)

# Import aspect
Aspect <- raster("aspect_output.tif")
st_crs(Aspect)
plot(Aspect)

# Import slope
Slope <- raster("slope_output.tif")
st_crs(Slope)
plot(Slope)

# Import GAP landcover data
GAPCover <- raster("GAP_output.tif")
st_crs(GAPCover)
plot(GAPCover)

# Alright, all data is in!
```

